### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-microprofile-openapi#1]
- [x] You either need to import all or import specific libraries: 
```
import org.eclipse.microprofile.openapi.annotations.*;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
```

- [ ] "Add OpenAPI annotations to the two JAX-RS methods in the src/main/java/io/openliberty/guides/inventory/InventoryResource.java class:"
I feel it's clearer to say "Open the ... file and update the class to the following code: ", since you actually change more than just adding annotations.

_But only annotations are added? None of the code is actually changed._

- [x] Also, it's either to say the `InventoryResource class` or `InventoryResource.java file`, not `InventoryResource.java class`

- [x] Formatting the code so that it looks cleaner on the testing site? https://qa-guides.mybluemix.net/guides/microprofile-openapi.html, now it looks a bit messy. Some lines are too long.

- [x] "/inventory/systems/{hostname}:" and "$ref: '#/components/schemas/Properties'"    This line of the OpenAPI tree is highlighted as red on the testing site, maybe you can adjust the format so it isn't recognized as incorrect syntax  on the website?

- [x] `Bootstrapping the OpenAPI tree using the OASFactory` The heading highlight looks weird on the testing site

- [ ] Personally I feel there are too many cases where you ask the reader to go to another link to learn more, or for more  info, code examples, etc in the guide (3-4 cases) , are those necessary?

_I'd say so. A lot of them are great examples from the demo apps Sasa's team wrote for OpenAPI_

- [x] Is there a better way to present the OASFactory in the first place? I've noticed you mentioned "For now, hold off from copying this code anywhere. It will fit nicely into the class you’ll create in the next section." The code appears twice in the guide. Why don't you talk about the next section first and then highlight the OASFactory?

_This section has been reworked._

**Comment by Kubik42** [comment]
Checked feedback incorporated as of 10b2d3ec0f8b19760bb0f41f480d4f464e68392e

**Comment by JunyiSun** [comment]
okay

**Comment by Kubik42** [comment]
Lets not close this yet, we should leave the other points up for discussion.
